### ISSUE TITLE
Tax Year start date is hard coded in a few places

### ISSUE THREAD

**Issue by MarkAKelly** [hmrc/income-tax-view-change-frontend#128]
I've noticed that the Tax Year is hard coded as a string and then turned into a LocalDate in a few places (IncomeSourcesModel, AccountingPeriodModel) and I thought it might be better to pull that out into a function that can be accessed from a shared utility.

I've made some proposed changes on the [BTAT-Refactor-TaxYear](https://github.com/hmrc/income-tax-view-change-frontend/compare/BTAT-Refactor-TaxYear) branch so let me know what people think of it.

**Comment by MJCallahanPage** [comment]
Think this can be closed as we have addressed this in subsquent changes for stories.
