### ISSUE TITLE
Accessibility Issues-ITVC

### ISSUE THREAD

**Issue by lakshmipochampally** [hmrc/income-tax-view-change-frontend#294]
-A heading level is skipped on ITVC home page from H1 to H3.
-In the ‘Statements’ area on the screen should the words ‘income tax’ have initial capital
letters?

**Comment by MJCallahanPage** [comment]
@lakshmipochampally this will be fixed by BTAT-2062

**Comment by MJCallahanPage** [comment]
Fixed by #313 #302 #305
