### ISSUE TITLE
Feed back text displayed on feedback page

### ISSUE THREAD

**Issue by mitchell1972** [hmrc/income-tax-view-change-frontend#314]
**This is a new service – your feedback will help us to improve it.** is displayed on all pages including the feedback page itself
![feedback](https://user-images.githubusercontent.com/13911129/37701866-896a27cc-2ce8-11e8-8d53-dc62e16e93fc.png)

**Comment by MJCallahanPage** [comment]
This was agreed as not an issue; closing.
