### ISSUE TITLE
Feedback page displayed for not enrolled user

### ISSUE THREAD

**Issue by mitchell1972** [hmrc/income-tax-view-change-frontend#315]
The feedback page is displayed when Sign out is clicked - for a user who's not enrolled

![image](https://user-images.githubusercontent.com/13911129/37702349-1c37881e-2cea-11e8-806c-502d14675965.png)

![image](https://user-images.githubusercontent.com/13911129/37702566-d9e9ed48-2cea-11e8-8239-230183a2a679.png)

**Comment by MJCallahanPage** [comment]
Discussed with Carl Shannon on 20/03/2018. Shared view was that this is so unlikely to happen that we would deal with it if it does.
